server:
  port: 9999
spring:
  application:
    name: member-admin
  profiles:
    active: dev
    include:
      - jwt
  config:
    import: optional:configserver:http://localhost:8888 # configserver와 통신 실패시 서버 실행을 멈추지 않으려면 optional 필수
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:member-admin;MODE=MYSQL
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: stage
---
spring:
  config:
    activate:
      on-profile: prod