integration:
  toast:
    email:
      header-key: X-Secret-Key
      base-url: https://api-mail.cloud.toast.com
      app-key: 4x0FwQ9AkfiM8v01
      secret-key: 5ZsrCqNI
      each-send-path: /email/v2.0/appKeys/{appKey}/sender/eachMail
      default-sender:
        name: BMT
        address: no-reply@bmt.co.kr
    sms:
      header-key: X-Secret-Key
      base-url: https://api-sms.cloud.toast.com
      app-key: t4TWYkw2j2YlcrXh
      secret-key: hVE9f2uo
      send-path: /sms/v3.0/appKeys/{appKey}/sender/sms
      default-sender:
        phone: 15777777
